### PR TITLE
Get this 🎉 Started

### PR DESCRIPTION
**Pull request by michael-hawker**
- Re-integrates PersonView from initial prototype with Provider system aligning better to [Microsoft Graph Toolkit](https://aka.ms/mgt)
- UWP XAML Provider Wrappers
- Supports Login/Logout
- Quick Sample Test app

### CODE REVIEW

**Comment by michael-hawker** [comment]
@azchohfi or @onovotny any ideas what [this error](https://dev.azure.com/dotnet/WindowsCommunityToolkit/_build/results?buildId=21344&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=036ed663-514a-59f3-0c88-23d2cf182147&l=949) is about? I thought we switched to strong naming? Or could this be some weird conflict of mismatching NuGet and MyGet feeds?

```
2>CSC : error CS8002: Referenced assembly 'Microsoft.Toolkit.Uwp.UI, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [D:\a\1\s\Microsoft.Toolkit.Graph.Controls\Microsoft.Toolkit.Graph.Controls.csproj]
```

**Comment by onovotny** [comment]
IIRC, we only signed the netstandard and NET Framework things? I’d need to take a closer look. UWP ignores sting names.

**Comment by michael-hawker** [comment]
Thanks for the background @onovotny, I'm wondering why it's complaining then.  Very odd.  I'll try switching to the MyGet feed for the control package too and see if that makes any difference.  I'll need to do that later anyway once Shane's PR goes in on the other repo.

**Comment by michael-hawker** [comment]
Hey @onovotny,

I tried switching the `Microsoft.Toolkit.Uwp.UI` reference to the MyGet version instead of the NuGet one, that got rid of the strong name issue, but then locally is giving me this:
```
       "C:\code\Graph-Controls\Windows-Toolkit-Graph-Controls.sln" (Build target) (1) ->
       "C:\code\Graph-Controls\Microsoft.Toolkit.Graph.Controls\Microsoft.Toolkit.Graph.Controls.csproj" (default targe
       t) (2) ->
       (_ShowMissingLanguageTargetsError target) ->
         C:\Users\mhawker\.nuget\packages\msbuild.sdk.extras\2.0.43\Build\LanguageTargets\CheckMissing.targets(37,5): e
       rror : The specified language targets for uap10.0.16299 is missing. Ensure correct tooling is installed for 'uap
       '. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WindowsXaml\v16.0\
       Microsoft.Windows.UI.Xaml.CSharp.targets' [C:\code\Graph-Controls\Microsoft.Toolkit.Graph.Controls\Microsoft.Too
       lkit.Graph.Controls.csproj]
```

I have the 16299 SDK installed. Have you seen this type of error before?

**Comment by michael-hawker** [comment]
Suffice it to say, there were a couple of quirks, but the SampleApp was trying to build in the pipeline as well on the native chain and failing (which is something we don't do in the main repo).  Had to remove that.  Need to try adding a few things back in, like ARM, and see if that works.  Will try that in the morning.

Not sure if I should jump back in the commit chain and forward-fix from there for clean-up?

**Comment by michael-hawker** [comment]
Cleaned up and Merged as #4

**Pull request closed without merging**
